version: '3'

services:
    app-publisher:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - app-logs:/app/logs
        environment:
            - APP_ROLE=PUBLISHER
        command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh rabbitmq:5672 -- nodemon server.js"

    app-consumer:
        build: .
        volumes:
            - .:/app
            - /app/node_modules
            - app-logs:/app/logs
        environment:
            - APP_ROLE=CONSUMER
            - CONSUMER_QUEUE_ID=default
        command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh rabbitmq:5672 -- nodemon server.js"

    mongo:
        image: 'mongo'
        ports:
            - '27017:27017'
        volumes:
            - 'mongodb:/data/db'

    rabbitmq:
        image: 'rabbitmq:3-management'
        ports:
            - '5672:5672'
            - '15672:15672'

    redis:
        image: 'redis'
        ports:
            - '6379:6379'

volumes:
    mongodb:
        driver: local
    app-logs:
        driver: local
