version: '3'

services:
    app:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
        command: bash -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh rabbitmq:5672 -- forever -a -o /tmp/out.log -e /tmp/err.log --watch --watchDirectory ./api node_modules/@shopline/sl-express/lib/server.js"

    mongo:
        image: 'mongo'
        ports:
            - '27017:27017'
        volumes:
            - 'mongodb:/data/db'

    rabbitmq:
        image: 'rabbitmq:3-management'
        ports:
            - '5672:5672'
            - '15672:15672'

    redis:
        image: 'redis'
        ports:
            - '6379:6379'

volumes:
    mongodb:
        driver: local
