version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: "mongo"
    volumes:
      - "mongodb:/data/db"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: "redis"

volumes:
  mongodb:
    driver: local